vdct/ProjetDuMois

DEVELOP.md, db/00_init.sql, db/10_project_update.js
Fix #128 
Utilisation du timestamp OSH pour ne recompter que les jours nécessaires.
Le recomptage global projet par projet est possible en supprimant le fichier osh_timestamp comme indiqué dans DEVELOP.md
=> Modification du comptage projet

db/10_project_update.js
Je me suis aperçu que c'était mieux de réinitialiser le fichier osh_timestamp à la fin du process pour éviter de laisser toute erreur en aval comme acquise.
Corrections mineures sur l'appel à date
Et joyeux noël :)
=> Modification de la réinitialisation du fichier osh_timestamp

db/10_project_update.js, website/index.js
Suite à #132, je me suis aperçu que certaines entrées de la table pdm_feature_counts n'étaient pas dans l'ordre chronologique. Cette PR pour rétablir l'ordre sur le graphique des stats et un bug mineur dans le script project:update
=> Fix website feature counts order

DEVELOP.md, website/templates/components/map.pug, website/utils.js
Le dev en cours pour Enedis met en évidence que le zoom 7 ou 8 des tuiles vectorielles est un peu trop chargé pour les poteaux.  
J'ai donc pensé que ce serait pas mal de pouvoir définir un min/max zoom par datasource pour chaque projet.
Les valeurs par défaut sont conservées, il n'y a pas lieu de modifier les projets existants
=> Possibilité de définir min/maxzoom sur les datasources projets

db/10_project_update.js
Petit bug entraînant le calcul de points de stats ultérieurs à la date du jour.
Pour le refresh du 2021-01-01, on avait les points de temps
2020-12-31
2021-01-01
2021-01-02 (carrément)
Maintenant on doit avoir
2020-12-31 seulement
=> Fix jour en trop dans l'actualisation des counts projet

db/00_init.sql, db/12_projects_contribs.sql
Suppression de la colonne projet injustement ajouté lors de ma PR sur le suivi des projets en simultané.
Cela causait l'apparition de plusieurs utilisateurs du même nom sur le podium, suivant leur implication dans plusieurs projets ou non
Fix #144
=> Fix noms d'utilisateur en double dans le leaderboard

db/00_init.sql, db/10_project_update.js, db/11_changes_contribs.sql, db/12_projects_contribs.sql
Modifications de l'organisation du script de mise à jour des projets
* Une unique boucle itérant sur les projets désormais (contre deux avant), fusion du filtrage et des stats
* Calcul incrémental des changes et contributions. Le script travaille sur une place de temps bornée, supprime l'existant dans cette plage et n'ajoute que le nécessaire
Avant c'était l'intégralité des changes et contributions qui étaient supprimés puis recréés.
J'ai testé un recalcul complet puis un calcul quotidien et je confirme que 99% des données restent en place au second calcul, gain d'efficacité certain
Drop + create obligatoire des tables suivantes :
* pdm_leaderboard
* pdm_changes
* pdm_feature_counts
* pdm_user_contribs
* pdm_user_names
Fix #143 
Fix #156 
Il restera les notes à inclure à tout ça, tracé …
=> Calcul incremental des contributions

db/10_project_update.js
Ce matin j'ai été choqué de ne pas avoir vu apparaitre sur le graph ma contribution de l'avant-veille.
En regardant de plus près, je me suis aperçu que l'heure du jour de filtrage définie dans #154 était définie à 00:00 au lieu de 23:59.
=> Fix sur l'heure pour le jour de comptage project

DEVELOP.md, projects/2017-04_electionboard/info.json, projects/2018-07_substation/info.json, projects/2018-11_police/info.json, projects/2020-03_evcharging/info.json, projects/2020-04_covid19/info.json, projects/2020-09_aed/info.json, website/index.js, website/templates/components/map.pug, website/templates/components/map_sidebar_legend.pug, website/templates/style.css, website/utils.js
Modification du comportement des couches de fond de carte. Le besoin existait pour Enedis d'ajouter une couche technique par dessus le fond de carte.
Création des datasources "background", ajout de la BD Ortho à tous les projets existant. Ces couches sont visibles en tant que raster dans la légende de l'éditeur. Suppression du controle mapbox permettant de masquer/afficher la BD Ortho uniquement pour permettre des choses plus complètes dans la légende.
=> Ajout des datasources background

db/10_project_update.js
J'ai l'honneur de vous soumettre la merge request suivante.
En cherchant pourquoi je n'avais plus de décompte de contribution et de mise à jour de mon podium sur Enedis, je me suis rendu compte que mes tables pdm_projects et pdm_projects_points étaient vides. Ceci empêchant l'INSERT des contributions de la journée lors de l'update.
J'ai donc rajouté un petit check pour que le problème sorte dans les logs chaque jour :)
=> Ajout d'un check de prérequis en amont du script d'update projet

.gitignore, DEVELOP.fr.md, DEVELOP.md, Dockerfile, config.example.json, db/10_project_update.js, db/20_features_update.js, docker-compose.yml, dockerfiles/docker-entrypoint.sh, website/index.js
Adds a Dockerfile based upon nodejs to run website and planned tasks.  
It doesn't include a postgresql server that could be run from official image as to prevent any lag in maintenance.
See readme and develop for more information on how to build and run it.
Don't merge it directly, remains to be tested:
* Cron tasks (with and without imposm)
* Install/init
=> Add Nodejs Dockerfile

db/20_features_update.js, db/22_features_post_init.sql, dockerfiles/docker-entrypoint.sh
Il y avait un petit bug dans le script de feature_update, la variable `PSQL_DB` était encore utilisée au lieu de l'env `DB_URL`.
J'ai retiré l'execution de project_update dans la commande init, inutile et ajouté une commande d'uninstall dans le docker-entrypoint.
=> Fix variable indéfinie features_update

db/10_project_update.js, db/12_projects_contribs.sql, dockerfiles/docker-entrypoint.sh, website/index.js, website/locales/fr.json, website/templates/components/stats.pug, website/templates/pages/multi_projects.pug, website/utils.js
@flacombe Une petite PR sur laquelle j'aimerais avoir ton avis avant intégration :
- J'ai fait sauter les contraintes dans les stats liées à la date de fin d'un projet. Peu importe celle-ci, les stats sont générées depuis la date de lancement jusqu'à la date du jour.
- La date de fin du projet ne sert qu'à le mettre en avant sur la page d'accueil (noté "projets prioritaires"). Le nombre de jours restants d'un projet n'apparaît donc plus dans les stats.
- Si un projet a été commencé depuis plus de 2 mois, la génération des stats se fait en ne prenant que le premier jour de chaque mois + date du jour. Exemple : un projet lancé en août 2022 ira chercher les infos aux dates : 2022-08-01, 2022-09-01, 2022-10-01, 2022-10-12.
Tout ça améliore l'affichage des graphiques et accélère la génération …
=> Stats for long projects

DEVELOP.fr.md, DEVELOP.md, docker-compose.yml
Étant donnée que pg_tilserv doit tourner pour afficher les markers osm dans un layer et que c'est pas explicitement expliqué je l'ai rajouté dans le docker-compose avec l'image Docker recommandé directement par [l'équipe derrière le projet](https://github.com/CrunchyData/pg_tileserv#download).
=> feat: add pg_tileserv in docker-compose

dockerfiles/docker-entrypoint.sh
Je présume que c'est une erreur étant donné qu'il n'y a jamais de mention de `project_` dans le `package.json`
=> fix: typo missing 's'

website/utils.js
As I was trying to add a link with wms tiles I was blocked on level 19.
Documentation for Background imagery list vars minzoom and maxzoom but where not implemented.
=> feat: add zoom override for background sources

db/00_init.sql, db/30_projects_update.js
I found several bugs in the project update process (yes, again).
* Scripts splitting in #295 doesn't allow to use osh_timestamp any more to get project last update time since os file is updated prior to run projects_update_tmp.sh
* No primary keys were defined in pdm_projects and prm_projects_points tables
* User contrib were not inserted as time window was osh current time to osh current time
* Async truncate and insert queries to install projects in pdm_project table were inefficient as truncate was executed pretty always after the insert.
Then I propose the following changes:
* Create primary keys in pdm_projects and pdm_projects_points and stop truncating every day
* Create a lastupdate_date column in pdm_projects to store each project last update date, which could be different from …
=> Improve projects update timestamp, fixes 

DEVELOP.fr.md, DEVELOP.md, config.example.json, package-lock.json, package.json, website/index.js, website/templates/common/head.pug
As notified in #312 osm deprecated Oauth 1.0,  there is few modifications to be able to use PDM again.
- Update sendfile_osm_oauth_protector submodule
- Update osm-auth
- Update osm-request
=> osm now use only oauth2

DEVELOP.fr.md, DEVELOP.md, config.example.json, package-lock.json, package.json, website/index.js, website/templates/common/head.pug, website/templates/components/map.pug, website/templates/components/map_editor.pug, website/templates/components/stats.pug, website/templates/pages/map.pug, website/templates/pages/project.pug, website/templates/style.css, website/utils.js
Direct replacement of mapbox with maplibre 1.15.3.
It may need further work but it actually work as this.
Some dependencies like pic4carto still includes some Mapbox modules.
See https://framagit.org/Pic4Carto/Pic4Carto.js/-/issues/43 
Fix #297
=> Drop mapbox in favour of maplibre

projects/2018-07_substation/info.json
Openinframap have changed urls without Power parameter, power and label layers are now visible.
CC @flacombe require to also update url in Enedis projects
=> Fix openinframap url

DEVELOP.fr.md, DEVELOP.md, Dockerfile
This PR updates minimal requirements:
- Set 18.17.0 like the minimal version of node js (for website and docker server) -> I'm not sure users continue to use nodejs 12
- Set PostgreSQL 13 like minimal versions like specified in Dockerfile and docker-compose file
- Add requests module python requirements in french doc
- Add missing url of website at the end of the french doc
- Add new command in Dockerfile before download dependencies with apt like recommend [here](https://github.com/hadolint/hadolint/wiki/DL4006)
Just need help to test, I have tried with Github Actions, but I have error when I want build dockerfile
=> Upgrade minimal requirements

.gitignore, docs/DEVELOP.fr.md, docs/DEVELOP.md, website/index.js, website/locales/en.json, website/locales/fr.json, website/templates/components/stats.pug, website/templates/pages/project.pug, website/utils.js
Modification du front pour une meilleure lisibilité des projets "terminés" :
- Projet _fini-fini_ (`end_date` renseigné / `soft_end_date` vide) : carte de contribution désactivée, wording un peu différent
- Projet qui continue sa vie en autonomie (`end_date` vide / `soft_end_date` renseigné) : carte de contribution toujours active, wording identique à précédemment. Projet dans la liste des projets passés sur la page d'accueil
- Projet en cours (`end_date` vide / `soft_end_date` vide) : mis en avant sur l'accueil
Déployé sur projetdumois.fr @flacombe si tu veux tester, tous les projets sont en `end_date=null + soft_end_date=renseigné` sauf horaires durant le covid.
=> Distinguish in website soft/hard project ends
