vdct/ProjetDuMois

website/templates/map.pug

Ajout d'un bouton pour exporter les erreurs de la vue courante en KML

WIP - export KML

---

projects/2020-09_aed/info.json

Display notes with #deficoeur

---

DEVELOP.md
config.example.json
db/10_project_update.js
db/20_features_update.js
website/index.js

Suppression de l'utilisateur/password postgresql de la configuration au profit du fichier ~/.pgpass, plus sécurisé (et évite d'avoir à mettre des login/pass dans le git)

Suppression user/password postgresql en faveur du fichier .pgpass

---

.gitignore
DEVELOP.md
config.example.json
db/20_features_update.js
db/90_uninstall.sql

Ajout
- de la possibilité de se passer d'imposm
- de scripts de désinstallation
Mise à jour de la documentation

Option de desactivation d'imposm et script d'uninstall

---

DEVELOP.md
db/10_project_update.js
db/20_features_update.js

Suite à mon mail de ce soir, je me suis aperçu qu'il y avait des exécutions non nécessaires d'osmium qui tournaient encore dans le script features:update, lorsqu'imposm3 était désactivé.
Ma compréhension du fonctionnement n'était pas encore la meilleure, du coup j'ai oublié d'y ajouter ces parties dans les if.
Je pense qu'il reste des choses non nécessaires dans le script project:update, peux-tu me dire ce que tu en penses @PanierAvide s'il te plaît?
J'ajouterai ce qu'il faut à cette PR.

Fix utilisation non necessaire d'osmium en cas d'imposm desactivé

---

db/10_project_update.js
db/20_features_update.js

Fix absence du timestamp pour osmupdate lors des updates

---

DEVELOP.md
db/10_project_update.js

Cette PR pour permettre de définir des filtres osmium avec AND.
Il faut reproduire le modif de primitive à tous les niveaux : n/Enedis&n/power=pole,tower
Il n'y a pas de projets actuellement qui en ait besoin, j'en avait besoin pour Enedis.

Filtres Osmium avec AND logique

---

website/templates/components/map_editor.pug
website/templates/components/map_sidebar_feature.pug

Ajout d'un éditeur 2states pour mieux gérer les situations de tags avec yes uniquement
Fix #140

Editeur 2states

---

website/index.js
website/templates/pages/project.pug
website/utils.js

Ergonomie minimale permettant d'afficher plusieurs projets en cours.
* Généralisation de la fonction foldProjects
* Ajout des projets en cours autre que celui visible sur la page dans la liste des "autres projets", sous les données

Capacité du front à afficher plusieurs projets en cours

---

db/10_project_update.js

Fix  #153 
Cette PR réorganise l'utilisation des fichiers osh et osm.
Le script laisse existant pour chaque projet un fichier filtered.osh.pbf à la fin de l'execution.
Correction du bug de comptage pour les stats et amélioration des perfs en limitant le nombre d'écritures sur le disque. Des cp sont évitées, etc...
Les filtrages à base d'expression avec && resteront sous-optimaux tant qu'osmium ne traitera pas de lui-même ces && (on est obligé de filtrer consécutivement des fichiers alors qu'on pourrait le faire en une fois)

Script project:update plus efficace et nettoyage fichier osh

---

DEVELOP.fr.md
DEVELOP.md
config.example.json
db/00_init.sql
db/10_project_update.js
db/12_projects_contribs.sql
db/20_features_update.js
db/22_features_post_init.sql
website/index.js
website/locales/en.json
website/locales/fr.json
website/projects.js
website/templates/components/stats.pug
website/templates/layout.pug
website/templates/pages/project.pug
website/templates/style.css
website/utils.js

Fixes #155 
@flacombe si tu as possibilité de tester et vérifier qu'il n'y a pas de soucis au niveau de ton instance

Display contribution statistics per boundary

---

db/20_features_update.js

Update mineur qui permet de ne pas définir de mapping lorsqu'imposm n'est pas activé dans un projet

Fix feature update script

---

website/templates/pages/project.pug

* Fix des liens vers les données externes
* Ajout d'une catégorie à part entière pour les autres projets en cours si nécessaire

Fix liens données et meilleure séparation entre données et projets

---

website/index.js

Suppression de la fonction get_points oubliée dans website/index.js

---

package.json
website/index.js
website/locales/en.json
website/templates/common/body_header.pug
website/templates/layout.pug
website/templates/pages/about.pug
website/templates/pages/error.pug
website/templates/pages/multi_projects.pug
website/templates/pages/project.pug

Je propose les modifications suivantes :
- Allégement du footer en envoyant le README dans une page A propos digne de ce nom
- Ajout du numéro de version dans le titre comme demandé (j'ai mis 0.5.0 arbitrairement)
Closes #273

Création de la page about, libération du footer et ajout de la version dans le titre

---

projects/2020-03_evcharging/howto.md
projects/2020-03_evcharging/info.json

Je propose les modifications suivantes du projet bornes de recharges.
Ceci pour préparer un challenge à venir avec Enedis
* Révision de la courte description
* Complément dans le howto
* Changement des dates, du 1er février au 31 mars.
* Retrait du lien vers le précédent article de 2020, dans l'attente d'une annonce plus actuelle
Closes #288

Update du projet bornes de recharges

---

projects/2017-07_busstop/howto.md
projects/2017-07_busstop/info.json
projects/2018_03_toilets/howto.md
projects/2018_03_toilets/info.json

Dans l'idée d'aller vers une instance avec toutes les analyses d'intégration opendata (#293 ), j'ai créé la conf' pour 2 projets finis qui ont une analyse Osmose

Ajout de 2 précédents pdm

---

projects/2020-03_evcharging/info.json

Correction de la date de départ du projet IRVE.
Closes #288

Fix date de début projet irve

---

DEVELOP.fr.md
DEVELOP.md
db/20_features_update.js
dockerfiles/docker-entrypoint.sh

J'ajoute la commande `update_daily` pour éviter d'avoir à viser juste dans les délais d’enchaînement des différentes commandes
Il suffit d'ajouter update_daily dans la crontab et ca marche désormais.
A noter que l'étape features:update ne produit aucun effet dans le cas où imposm est désactivé dans la configuration

Ajout d'une commande de mise à jour quotidienne

---

projects/2018_03_toilets/info.json
website/images/badges/busstop.mini.svg
website/images/badges/busstop.svg
website/images/badges/toilets.mini.svg
website/images/badges/toilets.svg

thanks to @overflorian
fix #298

add badges images for 2 old ProjectOfTheMonths

---

DEVELOP.fr.md
DEVELOP.md
config.example.json
website/templates/common/head.pug

Add Matomo support in projetdumois, with customizable host and website

Add configurable Matomo handler

---

website/index.js

Petit oubli lors du rebase avec oAuth2

Fix maplibre/mapbox on index

---

projects/2017-04_electionboard/info.json
projects/2018-11_police/info.json

Update http to https

---

db/00_init.sql
db/10_features_update.js

En lien avec #331, quelques correctifs nécessaires lors d'une initialisation complète @flacombe

Processing fixes

---

db/20_changes_update.js
db/23_changes_boundary.sql
projects/2017-04_electionboard/info.json
projects/2017-07_busstop/info.json
projects/2018-07_substation/info.json
projects/2018-11_police/info.json
projects/2018_03_toilets/info.json
projects/2020-03_evcharging/info.json
projects/2020-09_aed/info.json
projects/2021-05_laboratory/info.json

Another batch of fixes, one for a SQL request that has a comma misplaced, and the other for safer handling of no `end_date` defined in project JSON config file. @flacombe

Minor fixes on processing

---

db/20_changes_update.js
db/30_projects_update.js

Les changements suivants permettent d'améliorer la mise à jour quotidienne des projets
- Prise en compte de la date effective des changes rapatriés par osmupdate comme référence au lieu de la date courant ou de fin de projet
- Amélioration de l'algorithme de calcul des dates pour les dénombrements, avec la prise en compte des mises à jour quotidiennes
Ne pas se fier au nom de la branche, je pensais résoudre #337 mais c'est encore en discussion

Improve changes update time window

---

db/10_features_update.js
dockerfiles/docker-entrypoint.sh
docs/DEVELOP.fr.md
docs/DEVELOP.md

Juste ajouté une entrée au Docker pour pouvoir lancer le `imposm run` comme les autres commandes, avec le bout de doc qui va bien.

Add script for Docker Imposm update #289
